# Generated by Django 4.2.18 on 2025-02-10 21:28

from django.db import migrations, models
import todolist.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('target_date_project', models.DateField(default=todolist.models.Project.default_target_date)),
            ],
        ),
    ]
