# Generated by Django 4.2.18 on 2025-02-11 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import todolist.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='historic_target_date_project',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('target_date_task', models.DateField(default=todolist.models.default_target_date)),
                ('done', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('historic_target_date_task', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.category')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='todolist.project')),
            ],
        ),
    ]
